### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by Marty19** [bonesoul/hypepool#73]
Trying to compile on Ubuntu 14.04, dotnet 2.1.4, nodejs 10.1.0 and getting errors:

Utils/Helpers/Time/FastClock.cs(29,34): error CS0234: The type or namespace name 'Exporters' does not exist in the namespace 'BenchmarkDotNet.Attributes' (are you missing an assembly reference?) [/home/wallets/hypepool/src/Tests/Hypepool.Benchmarks/Hypepool.Benchmarks.csproj]
Utils/Helpers/Time/FastClock.cs(30,34): error CS0234: The type or namespace name 'Jobs' does not exist in the namespace 'BenchmarkDotNet.Attributes' (are you missing an assembly reference?) [/home/wallets/hypepool/src/Tests/Hypepool.Benchmarks/Hypepool.Benchmarks.csproj]

Any suggestions?

Thanks

**Comment by Marty19** [comment]
Reverted change "Merge pull request #55 from bonesoul/renovate/benchmarkdotnet-0.x" and compilation works ok.
